#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM  10
#define CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM 32
#define CONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM 32
#define CONFIG_ESP_WIFI_TX_BA_WIN             6
#define CONFIG_ESP_WIFI_RX_BA_WIN             6
#define CONFIG_ESP_WIFI_TX_BUFFER_TYPE        1

#endif // WIFI_CONFIG_H